/**
 * Created by bhalvers on 5/1/16.
 */
import angular from 'angular';

// import config files
import constants from './config/app.constants';
import appConfig from './config/app.config';
import appRun from './config/app.run';
import 'angular-ui-router';
// import templates file (generated by gulp)
import './config/app.templates';
import './layout';
import './components';
import './table';
import './services';

const requires = [
	'ui.router',
	'templates',
	'app.layout',
	'app.components',
	'app.table',
	'app.services'
];

window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
	strictDi: true
});